### ISSUE TITLE
error

### ISSUE THREAD

**Issue by CXW0504** [fxtxkktv/lnmVPN#3]
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/lnmVPN/venv/lib/python2.7/site-packages/gevent/baseserver.py", line 26, in _handle_and_close_when_done
    return handle(*args_tuple)
  File "/lnmVPN/venv/lib/python2.7/site-packages/gevent/server.py", line 201, in wrap_socket_and_handle
    with _closing_socket(self.wrap_socket(client_socket, **self.ssl_args)) as ssl_socket:
  File "/lnmVPN/venv/lib/python2.7/site-packages/gevent/_sslgte279.py", line 695, in wrap_socket
    ciphers=ciphers)
  File "/lnmVPN/venv/lib/python2.7/site-packages/gevent/_sslgte279.py", line 270, in __init__
    raise x
SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:618)
2019-10-23T00:31:33Z <Greenlet "Greenlet-0" at 0x7f575920d470: _handle_and_close_when_done(<bound method WSGIServer.wrap_socket_and_handle of, <bound method WSGIServer.do_close of <WSGIServer a, (<socket at 0x7f5758f8b8d0 fileno=[Errno 9] Bad fi)> failed with SSLError

**Comment by fxtxkktv** [comment]
ssl连接警示  不影响运行
